server:
  port: 8081 #为了以后访问项目不用写端口号
  servlet:
    context-path:  #为了以后访问项目不用写项目名
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mentalhealth?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  #数据库同步代码
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true      #dao操作时，显示sql语句
